// Optional starter content (ported from seed.py). Generic concept/formula cards
// written from scratch — format examples, not a substitute for real material.

export const SAMPLE_CARDS: [string, string, string, string][] = [
  ["ETH", "How many Standards of Professional Conduct are there, and name them by letter.",
    "Seven: I Professionalism, II Integrity of Capital Markets, III Duties to Clients, IV Duties to Employers, V Investment Analysis/Recommendations/Actions, VI Conflicts of Interest, VII Responsibilities as a Member/Candidate.", "core,memorize"],
  ["ETH", "What is the difference between the Code of Ethics and the Standards of Conduct?",
    "The Code states the broad ethical principles; the Standards give the specific, enforceable rules that operationalize those principles.", "concept"],
  ["QM", "Future value of a single sum (annual compounding)?", "FV = PV x (1 + r)^n", "formula"],
  ["QM", "What does a confidence interval tell you?",
    "A range that, with a stated probability, is expected to contain the true population parameter given the sampling distribution.", "concept"],
  ["ECO", "Define price elasticity of demand.",
    "The percentage change in quantity demanded divided by the percentage change in price; measures responsiveness of demand to price.", "concept"],
  ["ECO", "What characterizes a perfectly competitive market?",
    "Many price-taking firms, identical products, no barriers to entry/exit, and firms earning zero economic profit in the long run.", "concept"],
  ["FSA", "State the basic accounting equation.", "Assets = Liabilities + Owners' Equity.", "formula"],
  ["FSA", "Which inventory method yields higher COGS when prices are rising?",
    "LIFO produces higher COGS (and lower ending inventory and net income) during rising prices versus FIFO.", "concept"],
  ["CI", "What is the difference between business risk and financial risk?",
    "Business risk comes from operations and demand (operating leverage); financial risk comes from the use of fixed-cost financing such as debt (financial leverage).", "concept"],
  ["CI", "Define weighted average cost of capital (WACC) conceptually.",
    "The blended after-tax required return on a firm's capital, weighting the cost of each source (debt, equity) by its proportion in the capital structure.", "concept"],
  ["EI", "Write the constant-growth (Gordon) dividend discount model.",
    "V0 = D1 / (r - g), where D1 is next year's dividend, r the required return, g the constant growth rate (r > g).", "formula"],
  ["EI", "What does a price-to-earnings (P/E) ratio represent?",
    "Price per share divided by earnings per share — what investors pay per unit of earnings.", "concept"],
  ["FI", "What is the relationship between bond price and yield?",
    "Inverse: as required yield rises, bond price falls, and vice versa.", "core"],
  ["FI", "Define duration in one sentence.",
    "A measure of a bond's price sensitivity to a change in interest rates (approximate % price change for a 1% yield change).", "concept"],
  ["DER", "What is the payoff of a long call option at expiration?",
    "max(0, S_T - X): zero if the underlying S_T is below the strike X, otherwise S_T minus X.", "formula"],
  ["DER", "Difference between a forward and a futures contract?",
    "Forwards are customized OTC contracts settled at maturity; futures are standardized, exchange-traded, and marked to market daily.", "concept"],
  ["AI", "Name common categories of alternative investments.",
    "Hedge funds, private equity, real estate, commodities, and infrastructure.", "memorize"],
  ["AI", "Why are alternatives used in a portfolio?",
    "For diversification (low correlation with traditional assets) and potential for higher returns, accepting lower liquidity and higher fees.", "concept"],
  ["PM", "What two components make up an asset's total risk in the CAPM framework?",
    "Systematic (market) risk, which is priced, and unsystematic (firm-specific) risk, which is diversifiable and not rewarded.", "concept"],
  ["PM", "Write the Capital Asset Pricing Model.", "E(Ri) = Rf + Beta_i x (E(Rm) - Rf).", "formula"],
];

export const SAMPLE_QUESTIONS: [string, string, string, string, string, string, string][] = [
  ["ETH", "Under the Standards, when a member's responsibilities conflict, which duty generally takes priority?",
    "Duty to employer", "Duty to comply with applicable law and the Standards", "Duty to self", "B",
    "Members must place integrity of the profession and compliance with law/Standards above other interests; the most stringent applicable rule governs."],
  ["QM", "If interest is compounded more frequently, the effective annual rate (EAR) will:",
    "Decrease", "Stay the same", "Increase", "C",
    "More frequent compounding increases EAR for a given stated annual rate."],
  ["FSA", "During a period of rising prices, FIFO relative to LIFO will report:",
    "Lower net income", "Higher ending inventory", "Higher COGS", "B",
    "FIFO leaves newer, higher-cost units in ending inventory, so ending inventory is higher and COGS lower than under LIFO."],
  ["FI", "All else equal, a bond with a longer maturity will have:",
    "Lower interest-rate sensitivity", "Higher interest-rate sensitivity", "No change in sensitivity", "B",
    "Longer maturity generally increases duration and therefore price sensitivity to yield changes."],
  ["EI", "In the Gordon growth model, holding D1 and g constant, a higher required return r leads to:",
    "A higher value", "A lower value", "An unchanged value", "B",
    "Value = D1/(r-g); increasing r widens the denominator, lowering the present value."],
  ["DER", "The maximum loss to the buyer of a call option is:",
    "Unlimited", "The premium paid", "The strike price", "B",
    "A long call's downside is limited to the premium; the holder simply lets the option expire."],
  ["PM", "According to the CAPM, the only risk that is compensated with higher expected return is:",
    "Total risk", "Unsystematic risk", "Systematic (market) risk", "C",
    "Diversifiable (unsystematic) risk can be eliminated, so only systematic risk is priced."],
  ["ECO", "If demand is price elastic, a price increase will cause total revenue to:",
    "Increase", "Decrease", "Stay the same", "B",
    "When demand is elastic, quantity falls proportionally more than price rises, reducing revenue."],
  ["CI", "Higher operating leverage tends to increase a firm's:",
    "Financial risk", "Business risk", "Liquidity", "B",
    "Operating leverage magnifies the effect of sales changes on operating income, raising business risk."],
  ["AI", "Compared with traditional assets, alternative investments typically have:",
    "Higher liquidity", "Lower fees", "Lower liquidity and higher fees", "C",
    "Alternatives are generally less liquid and carry higher management/performance fees."],
];
